CREATE TABLE Station (idStation number(10) NOT NULL, nameStation varchar2(100) NOT NULL, stationTypeId number(10) NOT NULL, PRIMARY KEY (idStation));
CREATE TABLE Line (id number(10) NOT NULL, nameLine varchar2(100) NOT NULL, ownerId varchar2(100) NOT NULL, startStation number(10) NOT NULL, endStation number(10) NOT NULL, gaugeId number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE LineSegment (id number(10) NOT NULL, maximumWeigh number(10) NOT NULL, lenght number(10) NOT NULL, isElectrified number(10) NOT NULL, segmantesOrder number(10) NOT NULL, lineSegmentsTypeid number(10) NOT NULL, lineId number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE LineSegmentsType (id number(10) NOT NULL, description varchar2(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Wagon (numberWagon number(10) NOT NULL, weight number(10) NOT NULL, yearOfEntry number(10) NOT NULL, wagonModelId number(10) NOT NULL, operator varchar2(100) NOT NULL, PRIMARY KEY (numberWagon));
CREATE TABLE Locomotive (numberLocomotive number(10) NOT NULL, name varchar2(100) NOT NULL, yearOfEntry number(10) NOT NULL, operationalSpeed number(10) NOT NULL, model number(10) NOT NULL, operator varchar2(100) NOT NULL, PRIMARY KEY (numberLocomotive));
CREATE TABLE LocomotiveFuelType (id number(10) NOT NULL, description varchar2(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE WagonsType (id number(10) NOT NULL, description varchar2(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE StationType (id number(10) NOT NULL, description varchar2(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Operator (vatNumber varchar2(100) NOT NULL, name varchar2(100) NOT NULL, shortName varchar2(100) NOT NULL, PRIMARY KEY (vatNumber));
CREATE TABLE Gauge (idGauge number(10) NOT NULL, measure number(10) NOT NULL, PRIMARY KEY (idGauge));
CREATE TABLE Bogies (id number(10) NOT NULL, nameBogie varchar2(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE LocomotiveModel (id number(10) NOT NULL, make varchar2(100) NOT NULL, modelName varchar2(100) NOT NULL, power number(10) NOT NULL, maxSpeed number(10) NOT NULL, weight number(10) NOT NULL, length number(10) NOT NULL, width number(10) NOT NULL, height number(10) NOT NULL, traction number(10) NOT NULL, locomotiveFuelTypeId number(10) NOT NULL, bogiesId number(10) NOT NULL, gaugeId number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE WagonModel (id number(10) NOT NULL, nameModel varchar2(100) NOT NULL, maker varchar2(100) NOT NULL, length number(10) NOT NULL, width number(10) NOT NULL, height number(10) NOT NULL, maxSpeed number(10) NOT NULL, payload number(10) NOT NULL, volume number(10) NOT NULL, bogiesId number(10) NOT NULL, wagonsTypeId number(10) NOT NULL, gaugeId number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Electric (id number(10) NOT NULL, voltage number(10) NOT NULL, frequency number(10) NOT NULL, locomotiveFuelType number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Diesel (id number(10) NOT NULL, combustivelCapacity number(10) NOT NULL, locomotiveFuelType number(10) NOT NULL, PRIMARY KEY (id));
ALTER TABLE LineSegment ADD CONSTRAINT FKLineSegmen53814 FOREIGN KEY (lineSegmentsTypeid) REFERENCES LineSegmentsType (id);
ALTER TABLE LocomotiveModel ADD CONSTRAINT FKLocomotive878941 FOREIGN KEY (locomotiveFuelTypeId) REFERENCES LocomotiveFuelType (id);
ALTER TABLE WagonModel ADD CONSTRAINT FKWagonModel973052 FOREIGN KEY (wagonsTypeId) REFERENCES WagonsType (id);
ALTER TABLE LineSegment ADD CONSTRAINT FKLineSegmen635385 FOREIGN KEY (lineId) REFERENCES Line (id);
ALTER TABLE Station ADD CONSTRAINT FKStation307371 FOREIGN KEY (stationTypeId) REFERENCES StationType (id);
ALTER TABLE Line ADD CONSTRAINT FKLine939789 FOREIGN KEY (ownerId) REFERENCES Operator (vatNumber);
ALTER TABLE Line ADD CONSTRAINT FKLine995900 FOREIGN KEY (startStation) REFERENCES Station (idStation);
ALTER TABLE Line ADD CONSTRAINT FKLine43948 FOREIGN KEY (endStation) REFERENCES Station (idStation);
ALTER TABLE Line ADD CONSTRAINT FKLine888167 FOREIGN KEY (gaugeId) REFERENCES Gauge (idGauge);
ALTER TABLE Locomotive ADD CONSTRAINT FKLocomotive500975 FOREIGN KEY (model) REFERENCES LocomotiveModel (id);
ALTER TABLE LocomotiveModel ADD CONSTRAINT FKLocomotive789504 FOREIGN KEY (gaugeId) REFERENCES Gauge (idGauge);
ALTER TABLE WagonModel ADD CONSTRAINT FKWagonModel456712 FOREIGN KEY (bogiesId) REFERENCES Bogies (id);
ALTER TABLE LocomotiveModel ADD CONSTRAINT FKLocomotive181207 FOREIGN KEY (bogiesId) REFERENCES Bogies (id);
ALTER TABLE Wagon ADD CONSTRAINT FKWagon68456 FOREIGN KEY (wagonModelId) REFERENCES WagonModel (id);
ALTER TABLE WagonModel ADD CONSTRAINT FKWagonModel544166 FOREIGN KEY (gaugeId) REFERENCES Gauge (idGauge);
ALTER TABLE Wagon ADD CONSTRAINT FKWagon206763 FOREIGN KEY (operator) REFERENCES Operator (vatNumber);
ALTER TABLE Locomotive ADD CONSTRAINT FKLocomotive366773 FOREIGN KEY (operator) REFERENCES Operator (vatNumber);
ALTER TABLE Electric ADD CONSTRAINT FKElectric961289 FOREIGN KEY (locomotiveFuelType) REFERENCES LocomotiveFuelType (id);
ALTER TABLE Diesel ADD CONSTRAINT FKDiesel395266 FOREIGN KEY (locomotiveFuelType) REFERENCES LocomotiveFuelType (id);
